# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import micro_registry.registry_pb2 as registry__pb2

GRPC_GENERATED_VERSION = '1.66.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in registry_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RegistryServiceStub(object):
    """Define the gRPC service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterClass = channel.unary_unary(
                '/registry.RegistryService/RegisterClass',
                request_serializer=registry__pb2.RegisterClassRequest.SerializeToString,
                response_deserializer=registry__pb2.RegisterClassResponse.FromString,
                _registered_method=True)
        self.CreateInstance = channel.unary_unary(
                '/registry.RegistryService/CreateInstance',
                request_serializer=registry__pb2.CreateInstanceRequest.SerializeToString,
                response_deserializer=registry__pb2.CreateInstanceResponse.FromString,
                _registered_method=True)
        self.GetInstanceAttributes = channel.unary_unary(
                '/registry.RegistryService/GetInstanceAttributes',
                request_serializer=registry__pb2.GetInstanceAttributesRequest.SerializeToString,
                response_deserializer=registry__pb2.GetInstanceAttributesResponse.FromString,
                _registered_method=True)
        self.ListRegisteredClasses = channel.unary_unary(
                '/registry.RegistryService/ListRegisteredClasses',
                request_serializer=registry__pb2.Empty.SerializeToString,
                response_deserializer=registry__pb2.ListRegisteredClassesResponse.FromString,
                _registered_method=True)
        self.ListRegisteredInstances = channel.unary_unary(
                '/registry.RegistryService/ListRegisteredInstances',
                request_serializer=registry__pb2.Empty.SerializeToString,
                response_deserializer=registry__pb2.ListRegisteredInstancesResponse.FromString,
                _registered_method=True)


class RegistryServiceServicer(object):
    """Define the gRPC service
    """

    def RegisterClass(self, request, context):
        """RPC to register a class
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateInstance(self, request, context):
        """RPC to create an instance of a registered class
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetInstanceAttributes(self, request, context):
        """RPC to get the attributes of an instance
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListRegisteredClasses(self, request, context):
        """RPC to list all registered classes
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListRegisteredInstances(self, request, context):
        """RPC to list all registered instances
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RegistryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterClass': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterClass,
                    request_deserializer=registry__pb2.RegisterClassRequest.FromString,
                    response_serializer=registry__pb2.RegisterClassResponse.SerializeToString,
            ),
            'CreateInstance': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateInstance,
                    request_deserializer=registry__pb2.CreateInstanceRequest.FromString,
                    response_serializer=registry__pb2.CreateInstanceResponse.SerializeToString,
            ),
            'GetInstanceAttributes': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInstanceAttributes,
                    request_deserializer=registry__pb2.GetInstanceAttributesRequest.FromString,
                    response_serializer=registry__pb2.GetInstanceAttributesResponse.SerializeToString,
            ),
            'ListRegisteredClasses': grpc.unary_unary_rpc_method_handler(
                    servicer.ListRegisteredClasses,
                    request_deserializer=registry__pb2.Empty.FromString,
                    response_serializer=registry__pb2.ListRegisteredClassesResponse.SerializeToString,
            ),
            'ListRegisteredInstances': grpc.unary_unary_rpc_method_handler(
                    servicer.ListRegisteredInstances,
                    request_deserializer=registry__pb2.Empty.FromString,
                    response_serializer=registry__pb2.ListRegisteredInstancesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'registry.RegistryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('registry.RegistryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RegistryService(object):
    """Define the gRPC service
    """

    @staticmethod
    def RegisterClass(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/registry.RegistryService/RegisterClass',
            registry__pb2.RegisterClassRequest.SerializeToString,
            registry__pb2.RegisterClassResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateInstance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/registry.RegistryService/CreateInstance',
            registry__pb2.CreateInstanceRequest.SerializeToString,
            registry__pb2.CreateInstanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetInstanceAttributes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/registry.RegistryService/GetInstanceAttributes',
            registry__pb2.GetInstanceAttributesRequest.SerializeToString,
            registry__pb2.GetInstanceAttributesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListRegisteredClasses(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/registry.RegistryService/ListRegisteredClasses',
            registry__pb2.Empty.SerializeToString,
            registry__pb2.ListRegisteredClassesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListRegisteredInstances(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/registry.RegistryService/ListRegisteredInstances',
            registry__pb2.Empty.SerializeToString,
            registry__pb2.ListRegisteredInstancesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
