# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: registry.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'registry.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eregistry.proto\x12\x08registry\"\x07\n\x05\x45mpty\"C\n\x14RegisterClassRequest\x12\x12\n\nclass_name\x18\x01 \x01(\t\x12\x17\n\x0f\x62\x61se_class_name\x18\x02 \x01(\t\"(\n\x15RegisterClassResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\xba\x01\n\x15\x43reateInstanceRequest\x12\x12\n\nclass_name\x18\x01 \x01(\t\x12\x15\n\rinstance_name\x18\x02 \x01(\t\x12\x43\n\nparameters\x18\x03 \x03(\x0b\x32/.registry.CreateInstanceRequest.ParametersEntry\x1a\x31\n\x0fParametersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\")\n\x16\x43reateInstanceResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"5\n\x1cGetInstanceAttributesRequest\x12\x15\n\rinstance_name\x18\x01 \x01(\t\"\x9f\x01\n\x1dGetInstanceAttributesResponse\x12K\n\nattributes\x18\x01 \x03(\x0b\x32\x37.registry.GetInstanceAttributesResponse.AttributesEntry\x1a\x31\n\x0f\x41ttributesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"4\n\x1dListRegisteredClassesResponse\x12\x13\n\x0b\x63lass_names\x18\x01 \x03(\t\"9\n\x1fListRegisteredInstancesResponse\x12\x16\n\x0einstance_names\x18\x01 \x03(\t2\xcc\x03\n\x0fRegistryService\x12P\n\rRegisterClass\x12\x1e.registry.RegisterClassRequest\x1a\x1f.registry.RegisterClassResponse\x12S\n\x0e\x43reateInstance\x12\x1f.registry.CreateInstanceRequest\x1a .registry.CreateInstanceResponse\x12h\n\x15GetInstanceAttributes\x12&.registry.GetInstanceAttributesRequest\x1a\'.registry.GetInstanceAttributesResponse\x12Q\n\x15ListRegisteredClasses\x12\x0f.registry.Empty\x1a\'.registry.ListRegisteredClassesResponse\x12U\n\x17ListRegisteredInstances\x12\x0f.registry.Empty\x1a).registry.ListRegisteredInstancesResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'registry_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREATEINSTANCEREQUEST_PARAMETERSENTRY']._loaded_options = None
  _globals['_CREATEINSTANCEREQUEST_PARAMETERSENTRY']._serialized_options = b'8\001'
  _globals['_GETINSTANCEATTRIBUTESRESPONSE_ATTRIBUTESENTRY']._loaded_options = None
  _globals['_GETINSTANCEATTRIBUTESRESPONSE_ATTRIBUTESENTRY']._serialized_options = b'8\001'
  _globals['_EMPTY']._serialized_start=28
  _globals['_EMPTY']._serialized_end=35
  _globals['_REGISTERCLASSREQUEST']._serialized_start=37
  _globals['_REGISTERCLASSREQUEST']._serialized_end=104
  _globals['_REGISTERCLASSRESPONSE']._serialized_start=106
  _globals['_REGISTERCLASSRESPONSE']._serialized_end=146
  _globals['_CREATEINSTANCEREQUEST']._serialized_start=149
  _globals['_CREATEINSTANCEREQUEST']._serialized_end=335
  _globals['_CREATEINSTANCEREQUEST_PARAMETERSENTRY']._serialized_start=286
  _globals['_CREATEINSTANCEREQUEST_PARAMETERSENTRY']._serialized_end=335
  _globals['_CREATEINSTANCERESPONSE']._serialized_start=337
  _globals['_CREATEINSTANCERESPONSE']._serialized_end=378
  _globals['_GETINSTANCEATTRIBUTESREQUEST']._serialized_start=380
  _globals['_GETINSTANCEATTRIBUTESREQUEST']._serialized_end=433
  _globals['_GETINSTANCEATTRIBUTESRESPONSE']._serialized_start=436
  _globals['_GETINSTANCEATTRIBUTESRESPONSE']._serialized_end=595
  _globals['_GETINSTANCEATTRIBUTESRESPONSE_ATTRIBUTESENTRY']._serialized_start=546
  _globals['_GETINSTANCEATTRIBUTESRESPONSE_ATTRIBUTESENTRY']._serialized_end=595
  _globals['_LISTREGISTEREDCLASSESRESPONSE']._serialized_start=597
  _globals['_LISTREGISTEREDCLASSESRESPONSE']._serialized_end=649
  _globals['_LISTREGISTEREDINSTANCESRESPONSE']._serialized_start=651
  _globals['_LISTREGISTEREDINSTANCESRESPONSE']._serialized_end=708
  _globals['_REGISTRYSERVICE']._serialized_start=711
  _globals['_REGISTRYSERVICE']._serialized_end=1171
# @@protoc_insertion_point(module_scope)
